language: ruby
rvm:
- 1.9.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:drop db:create db:migrate
- bundle exec jammit
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: mlinnem@us.ibm.com
  organization: micahslittleorg
  space: dev
  on:
    repo: mlinnem/botharetotallyenraged
  password:
    secure: OpLnmCL7Icly5i/a6oHf/UiZADQjB1JXvVXhWTz+dwrmc/5NHgOjRQ51zbinwvuyth55n/MesFK7PNvC2/2mY3Bd/xBOmoFqnEzBEw506uIKhL0NCkym1Y7n+g9lE8DHVqxTFddZfARghDJBSz6lRXefA+QIzEOozxpnPcy2NAY=
