language: ruby
rvm:
- 1.9.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- "sh start.sh"
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: mlinnem@us.ibm.com
  organization: micahslittleorg
  space: dev
  on:
    repo: mlinnem/botharetotallyenraged
  password:
    secure: SpF0RkLkHmZ/tAChMwxRwtIM6wO+ir3lFCkKGZX8nQ2XxaZ25y97lYQqQGanwrIHKenxnL5+bfrPAi0knEQyBuMmRyNJ52WZrNBfGJTJSmZ7Kf3pF4MbBHGdsKDNAuYw2PXc58RRCcD9dtOaqtvfmxgE7On7K3O4dd2seOlq2zE=
