language: ruby
rvm:
  - 1.9.3
before_script: 
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:drop db:create db:migrate
  - bundle exec jammit

script: "bundle exec rake test"

 deploy:
   edge: true
   provider: cloudfoundry
   username: mlinnem@us.ibm.com
   password: BoldFun1
   api: https://api.ng.bluemix.net
   organization: micahslittleorg
   space: dev
