#embed_assets: on
package_assets: off #TODO: Turn back on to start jammin' it again

javascripts:
    workspace:
        - public/javascripts/*.js

stylesheets:
    workspace:
        - public/stylesheets/*.css