development:
  adapter: postgresql
  encoding: unicode
  database: botharetotallyenraged
  pool: 5 
  username: micahlinnemeier
  password:



test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
  pool: 5
  encoding: unicode

quicktest_docker:
  adapter: postgresql
  database: botharetotallyenraged
  pool: 5
  username: postgres
  encoding: unicode