# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  encoding: unicode
  database: botharetotallyenraged
  pool: 5 
  username: micahlinnemeier
  password:



test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
  pool: 5
  encoding: unicode

  production:
    adapter: postgresql
    encoding: utf8
    reconnect: false
    pool: 5
    database: <%=ENV['OPENSHIFT_APP_NAME']%>
    username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
    password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
    host:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
    port:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>